apiVersion: apps/v1
kind: Deployment
metadata:
  name: backstage-demo
spec:
  selector:
    matchLabels:
      app: backstage-demo
  template:
    metadata:
      labels:
        app: backstage-demo
    spec:
      containers:
     
      - image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        name: backstage-demo

        env:
        - name: POSTGRES_PASSWORD
          value: {{ .Values.database.connection.password }}
        - name: POSTGRES_USER
          value: {{ .Values.database.connection.user }}
        - name: POSTGRES_HOST
          value: {{ .Values.database.connection.host }}
        
        ports:
        - name: http
          containerPort: 80